version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: autodraft-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: autodraft
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - autodraft-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: autodraft-backend
    restart: always
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/autodraft
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
      FRONTEND_URL: ${FRONTEND_URL:-http://localhost:3000}
      # Enable CORS for local frontend development
      CORS_ORIGINS: "http://localhost:3000"
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - backend_data:/app/generated_documents
      - backend_uploads:/app/uploads
    networks:
      - autodraft-network

volumes:
  postgres_data:
  backend_data:
  backend_uploads:

networks:
  autodraft-network:
    driver: bridge 